#include <windows.h>
#include <GL/gl.h>

#include "shader.h"  // generated by shader_minifier from shader.frag

#define GL_FRAGMENT_SHADER 0x8B30

typedef GLuint(WINAPI *PFNGLCREATESHADERPROGRAMVPROC)(GLenum, GLsizei, const char *const *);
typedef void(WINAPI *PFNGLUSEPROGRAMPROC)(GLuint);
typedef void(WINAPI *PFNGLUNIFORM3FPROC)(GLint, float, float, float);

// no CRT, but the compiler still wants this symbol for float usage
int _fltused;

static PIXELFORMATDESCRIPTOR pfd = {
    0, 0, PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER, 0, 32
};

// ---- music: 90s techno, no CRT (integer phases, parabolic sine, LCG noise) ----

#define SR 44100
#define STEP 4725                 // one 16th note at 140 BPM
#define SONGLEN (STEP * 16 * 32)  // 32 bars (~55 s), then waveOut loops it

static short sbuf[SONGLEN];

// acid bassline, semitones above A1; -1 = rest
static const signed char basspat[16] = {
    0, -1, 0, 12, 0, -1, 10, -1, 0, 0, 12, -1, 3, -1, 15, 12
};

// lead melody, 4 bars of 16ths in A minor, semitones above A3; -1 = rest
static const signed char melody[64] = {
    12, -1, 12, -1, 15, 12, 10, 12,  7, -1,  7, -1, 10,  7,  3,  7,
     5, -1,  5, -1,  8,  5,  3,  5,  0, -1,  3,  5,  7, 10, 12, 14,
    15, -1, 12, -1, 15, 17, 15, 12, 19, -1, 15, -1, 12, -1, 10, -1,
    12, 10,  7, 10, 12, -1, 14, -1, 15, 14, 12, 10,  7,  5,  3,  2,
};

// "vocal" anthem riff, semitones above A4; -1 = hold, -2 = release
// syncopated stabs (a written-out trance gate), big held octave in bar 4
static const signed char voxpat[64] = {
     0, -1, -2,  0, -1, -2,  3, -1, -2,  0, -1, -2,  7, -1, -1, -2,
     5, -1, -2,  5, -1, -2,  7, -1, -2,  3, -1, -2,  2, -1, -1, -2,
     0, -1, -2,  0, -1, -2,  3, -1, -2,  7, -1, -2, 10, -1, -1, -2,
    12, -1, -1, -1, -1, -1, -1, -1, 10, -1, -2,  7, -1, -2,  5, -1,
};

static float dbuf[STEP * 3];  // dotted-8th feedback delay line

// one entry shown per 2 bars, then the list wraps
static const char *greets[] = {
    "GREETINGS TO", "JARKKO", "JANI", "JUSSI", "JOHANNES",
    "PERTTU", "ARI-MATTI", "PETRI",
};
#define NGREETS (sizeof(greets) / sizeof(*greets))

static WAVEFORMATEX wfx = { WAVE_FORMAT_PCM, 1, SR, SR * 2, 2, 16, 0 };
static WAVEHDR whdr = {
    (LPSTR)sbuf, sizeof(sbuf), 0, 0, WHDR_BEGINLOOP | WHDR_ENDLOOP, (DWORD)-1
};

// parabolic sine approximation, good to ~3% — no CRT sinf available
static float ssin(float x)
{
    x -= (int)(x * .159155f) * 6.28319f;  // fistp rounds to nearest: wraps to [-pi, pi]
    return 1.27324f * x - .405285f * x * (float)fabs(x);
}

static void synth(void)
{
    float kph = 0, kf = 0, kenv = 0;           // kick: phase, falling pitch, env
    float henv = 0, hdec = 0, cenv = 0;        // hats, clap
    float benv = 0, fenv = 0, lp = 0, bp = 0;  // bass env, filter sweep, SVF state
    float mfr = 0, menv = 0;                   // lead: note freq, env
    float vfr = 440, vtf = 440, vgate = 0;     // vocal: pitch, glide target, gate
    float venv = 0, vvib = 0, vpw = 0;         // vocal: env, vibrato swell, wah
    unsigned bph = 0, bst = 0, mph = 0, mph2 = 0, vph = 0, seed = 1;
    for (int i = 0; i < SONGLEN; i++) {
        int step = i / STEP, bar = step >> 4;
        if (i % STEP == 0) {
            // four on the floor, one break bar every 16
            if ((step & 3) == 0 && (bar & 15) != 15) { kf = .004f; kenv = 1; }
            // hats on the "and" of each beat, last one per bar rings open
            if ((step & 3) == 2 && (bar & 15) > 1) {
                henv = .35f;
                hdec = (step & 15) == 14 ? .9995f : .999f;
            }
            if ((step & 7) == 4 && (bar & 15) > 3) cenv = .5f;  // clap on 2 and 4
            int n = basspat[step & 15];
            if (n >= 0) {
                float fr = 55;
                while (n--) fr *= 1.0594631f;  // 2^(1/12), no pow needed
                bst = (unsigned)(fr * 97391.5f);
                benv = .8f;
                fenv = .1f + .15f * (bar & 7) / 7.f;  // sweep opens over 8 bars
            }
            n = melody[step & 63];
            if (n >= 0) {
                mfr = 220;
                while (n--) mfr *= 1.0594631f;
                menv = .5f;
            }
            // vocal solo enters with the claps (bar 4 of each 16)
            n = voxpat[step & 63];
            if ((bar & 15) < 4 || n == -2) {
                vgate = 0;
            } else if (n >= 0) {
                vtf = 440;
                while (n--) vtf *= 1.0594631f;
                vgate = .38f;
                vvib = 0;     // vibrato swells in fresh on each note
                vpw = .1f;    // and the "mouth" reopens
            }
        }
        // kick: parabolic pseudo-sine with exponentially falling pitch
        kph += kf;
        kf *= .99955f;
        kenv *= .9997f;
        float frc = kph - (int)kph;  // [-.5,.5] (fistp rounds to nearest)
        float kick = 8 * frc * (.5f - (float)fabs(frc)) * kenv;
        // one LCG noise source feeds hats and clap
        seed = seed * 1103515245 + 12345;
        float ns = (int)seed * 4.6e-10f;
        float hat = ns * henv;
        henv *= hdec;
        float clap = ns * cenv;
        cenv *= .9985f;
        // acid bass: saw through a resonant SVF, cutoff decays per note
        bph += bst;
        float saw = (int)bph * 4.6e-10f * benv;
        benv *= .99955f;
        fenv *= .9994f;
        float cut = .04f + fenv;
        lp += cut * bp;
        bp += cut * (saw - lp - .35f * bp);
        // lead: SID pulse with vibrato/PWM plays throughout; the detuned saw
        // and dotted-8th echoes only join inside the cube (bars 8-15)
        unsigned mst = (unsigned)(mfr * (1 + .006f * ssin(i * .000855f)) * 97391.5f);
        mph += mst;
        mph2 += mst + (mst >> 8);
        float pw = .4f * ssin(i * .0001f);
        float tr = (bar & 15) > 7 ? 1.f : 0;
        float lead = ((int)mph * 4.66e-10f < pw ? .32f : -.32f) * menv
                   + (int)mph2 * 7e-11f * menv * tr;
        menv *= .9994f;
        // vocal: quick scoop onto each note, light vibrato, pulse-width wah,
        // ducked against the kick for the sidechain pump
        vfr += (vtf - vfr) * .002f;
        vvib += (1 - vvib) * .00012f;
        venv += (vgate - venv) * .0008f;
        vpw += (.45f - vpw) * .00015f;
        vph += (unsigned)(vfr * (1 + .008f * vvib * ssin(i * .000784f)) * 97391.5f);
        float voc = ((int)vph * 4.66e-10f < vpw ? .5f : -.5f) * venv * (1 - kenv * .7f);
        int di = i % (STEP * 3);
        float wet = lead + voc + dbuf[di] * .55f * tr;
        dbuf[di] = wet;
        float s = kick * .9f + hat + clap + (lp + bp * .5f) * .9f + wet * .9f;
        s = s / (1 + (float)fabs(s));  // soft clip
        sbuf[i] = (short)(s * 32000.f);
    }
}

void entrypoint(void)
{
    synth();
    HWAVEOUT wo;
    waveOutOpen(&wo, WAVE_MAPPER, &wfx, 0, 0, 0);
    waveOutPrepareHeader(wo, &whdr, sizeof(whdr));
    waveOutWrite(wo, &whdr, sizeof(whdr));

    HWND wnd = CreateWindowExA(0, "static", 0, WS_VISIBLE | WS_CAPTION | WS_SYSMENU,
                               100, 100, 1280, 720, 0, 0, 0, 0);
    RECT rc;
    GetClientRect(wnd, &rc);
    int w = rc.right, h = rc.bottom;
    HDC dc = GetDC(wnd);
    SetPixelFormat(dc, ChoosePixelFormat(dc, &pfd), &pfd);
    wglMakeCurrent(dc, wglCreateContext(dc));

    const char *src = shader_frag;
    GLuint prog = ((PFNGLCREATESHADERPROGRAMVPROC)wglGetProcAddress("glCreateShaderProgramv"))(
        GL_FRAGMENT_SHADER, 1, &src);
    PFNGLUSEPROGRAMPROC useProgram = (PFNGLUSEPROGRAMPROC)wglGetProcAddress("glUseProgram");
    PFNGLUNIFORM3FPROC uniform3f = (PFNGLUNIFORM3FPROC)wglGetProcAddress("glUniform3f");

    // bake the ASCII range of a GDI font into GL display lists for the greets
    SelectObject(dc, CreateFontA(-40, 0, 0, 0, FW_BOLD, 0, 0, 0, 0, 0, 0, 0, 0, "Courier New"));
    wglUseFontBitmapsA(dc, 0, 128, 1000);
    glListBase(1000);

    static MMTIME mmt = { TIME_SAMPLES };
    DWORD next = GetTickCount();
    do {
        MSG msg;
        while (PeekMessageA(&msg, 0, 0, 0, PM_REMOVE))
            DispatchMessageA(&msg);
        // clock the whole intro off the audio position: beats stay sample-exact
        waveOutGetPosition(wo, &mmt, sizeof(mmt));
        float tm = (int)mmt.u.sample * (1.f / SR);
        useProgram(prog);
        uniform3f(0, (float)w, (float)h, tm);
        glRects(-1, -1, 1, 1);
        // text uses the fixed pipeline; .583 converts seconds to bars at 140 BPM
        useProgram(0);
        const char *s = greets[((int)(tm * .58333f) >> 1) % NGREETS];
        int len = lstrlenA(s);
        for (int i = 0; i < len; i++) {
            // per-character rainbow cycle and sine wave, centered line
            float ph = tm * 2 + i * .45f;
            glColor3f(.6f + .4f * ssin(ph),
                      .6f + .4f * ssin(ph + 2.1f),
                      .6f + .4f * ssin(ph + 4.2f));
            glRasterPos2f((i - len * .5f) * .038f,
                          -.7f + .07f * ssin(tm * 3 + i * .5f));
            glCallLists(1, GL_UNSIGNED_BYTE, s + i);
        }
        SwapBuffers(dc);
        next += 16;  // ~60 fps cap
        int wait = (int)(next - GetTickCount());
        if (wait > 0) Sleep(wait);
    } while (!GetAsyncKeyState(VK_ESCAPE) && IsWindow(wnd));

    ExitProcess(0);
}
